### ISSUE TITLE
Test dropdown with speakers, venues, translators, languages, classifications

### ISSUE THREAD

**Issue by awesomepankaj** [Mindgreppers/DalaiLama#182]
Ensure migration script creates these tables correctly

**Comment by vaibhavmule** [comment]
Done with Venues, Languages, Classification. 

Speakers, Translator are remaining.

**Comment by vaibhavmule** [comment]
Speakers and Translator is not completed because Speaker and Translator just have person, languages fields and newly created dropdown not able to get suggestion on person field
